### ISSUE TITLE
Incompatibility with pyinstaller

### ISSUE THREAD

**Issue by dennisjs** [iotaledger/iota.py#324]
## Bug description

This isn't exactly a bug, but solidpython is currently incompatible with pyinstaller builds.  When building with pyinstaller, issues arise with 'scad_render_to_file'.  

Note that I found a workaround:  copy the 'pyproject.toml' file to the resultant exectuable's folder.  Also, 'include_orig_code = False' in scad_render_to_file, as this portion of the library also fails during the compile.

## Version

0.4.8

- PyOTA Version:
- Python Version: 3.8.2

## IOTA network

Which node are you connected to and which IOTA network is it in?

- Node URL:
- Network:

## Environment

What operating system are you using? Windows

- Operating system:
## Steps To reproduce the bug

Explain how the maintainer can reproduce the bug.

1. compile code with solid includes using pyinstaller
2. include a scad_render_to_file call
3. 

## Expected behaviour

Successful code execution, including SCAD rendering

## Actual behaviour

Code errors out with scad_render_to_file

## Errors
this line triggered the error:

file_out = sld.scad_render_to_file(cyl, out_dir=out_dir, file_header=f'$fn = {SEGMENTS};')

Traceback (most recent call last):
  File "site-packages\solid\solidpython.py", line 564, in _get_version
  File "site-packages\pkg_resources\__init__.py", line 481, in get_distribution
  File "site-packages\pkg_resources\__init__.py", line 357, in get_provider
  File "site-packages\pkg_resources\__init__.py", line 900, in require
  File "site-packages\pkg_resources\__init__.py", line 786, in resolve
pkg_resources.DistributionNotFound: The 'solidpython' distribution was not found and is required by the application

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "stlmod_gui.py", line 653, in <module>
  File "site-packages\solid\solidpython.py", line 503, in scad_render_to_file
  File "site-packages\solid\solidpython.py", line 572, in _get_version
  File "pathlib.py", line 1227, in read_text
  File "pathlib.py", line 1213, in open
  File "pathlib.py", line 1069, in _opener
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\dschis\\PycharmProjects\\stlmod\\dist\\stlmod_gui\\pyproject.toml'

<traceback object at 0x0D5BB668>

**Comment by todofixthis** [comment]
Hi @dennisjs I'm not sure I understand what this has to do with PyOTA.  Did you mean to post this to [SolidPython's issue tracker](https://github.com/SolidCode/SolidPython/issues)?

**Comment by dennisjs** [comment]
So sorry!  Yes, this was intended for SolidPython!
